"""empty message

Revision ID: 676b3b81f37e
Revises: 
Create Date: 2020-12-09 22:06:32.710742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676b3b81f37e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gnss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=16), nullable=False),
    sa.Column('num_satellites', sa.Integer(), nullable=False),
    sa.Column('num_frequencies', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('gnss_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gnss_id'], ['gnss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal')
    op.drop_table('gnss')
    # ### end Alembic commands ###
