"""empty message

Revision ID: 87f7ed7cc705
Revises: 676b3b81f37e
Create Date: 2020-12-11 23:04:16.740479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f7ed7cc705'
down_revision = '676b3b81f37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signal', 'gnss_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signal', 'gnss_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
